In [1]:
import numpy as np

# 1D Array (Vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr_2d)

# 3D Array (Tensor)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr_3d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


    np.array() converts Python lists into NumPy arrays

    Dimensions are determined by nesting levels

In [2]:
arr = np.array([1, 2, 3], dtype=np.float64)
print("Data type:", arr.dtype)

Data type: float64


    Controls memory usage and precision

    Common types: int32, float64, bool

In [4]:
arr = np.arange(6).reshape(2, 3)
print("Reshaped Array:\n", arr)

Reshaped Array:
 [[0 1 2]
 [3 4 5]]


    Changes dimensions without modifying data

    Total elements must remain the same

In [3]:
arr = np.arange(0, 10, 2)  # Start, Stop, Step
print("Arange Array:", arr)

Arange Array: [0 2 4 6 8]


    Similar to Python's range() but returns array

    Useful for creating sequences

In [5]:
arr = np.empty((2, 3))  # Shape only
print("Empty Array:\n", arr)

Empty Array:
 [[2.42350005e-316 0.00000000e+000 6.66232041e-310]
 [6.66229407e-310 6.66229407e-310 6.66229402e-310]]


    Faster initialization than zeros or ones

    Contains whatever values were in memory

In [6]:
arr = np.ones((2, 3))
print("Ones Array:\n", arr)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


    Creates array filled with 1.0

    Often used as initialization for algorithms

In [7]:
arr = np.zeros((2, 3))
print("Zeros Array:\n", arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


    Creates array filled with 0.0

    Common starting point for accumulators

In [8]:
lst = [1, 2, 3]
arr = np.asarray(lst)
print("Asarray:", arr)

Asarray: [1 2 3]


    Converts existing sequences to arrays

    Doesn't copy data if already an array

In [9]:
arr = np.array([[1, 9, 3], [4, 5, 6], [7, 8, 2]])

# Global maximum
print("Max value:", arr.max())
print("Max index:", np.argmax(arr))

# Row-wise maximum
print("Row max:", arr.max(axis=1))

# Column-wise maximum
print("Column max:", arr.max(axis=0))

Max value: 9
Max index: 1
Row max: [9 6 8]
Column max: [7 9 6]


    max() finds highest value

    argmax() returns index of maximum

    axis=1 operates on rows, axis=0 on columns

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Sum:", arr.sum())

Minimum: 1
Maximum: 6
Sum: 21


    Basic statistical operations

    Work on entire array by default

In [11]:
arr = np.array([1, 4, 9, 16])

print("Square roots:", np.sqrt(arr))
print("Standard deviation:", np.std(arr))

Square roots: [1. 2. 3. 4.]
Standard deviation: 5.678908345800274


    sqrt() computes element-wise square roots

    std() calculates standard deviation

In [12]:
arr = np.array([[3, 1], [4, 2]])

print("Flattened sort:", np.sort(arr, axis=None))
print("Row-wise sort:", np.sort(arr, axis=1))
print("Column-wise sort:", np.sort(arr, axis=0))

Flattened sort: [1 2 3 4]
Row-wise sort: [[1 3]
 [2 4]]
Column-wise sort: [[3 1]
 [4 2]]


    axis=None sorts flattened array

    axis=1 sorts each row

    axis=0 sorts each column

In [13]:
arr = np.array([[1, 2], [3, 4]])

print("Overall mean:", np.mean(arr))
print("Row means:", np.mean(arr, axis=1))
print("Column means:", np.mean(arr, axis=0))

Overall mean: 2.5
Row means: [1.5 3.5]
Column means: [2. 3.]


    Calculates arithmetic mean

    axis parameter controls direction

In [14]:
arr = np.array([[1, 2], [3, 4]])

# Add row
new_row = np.array([5, 6])
arr = np.vstack((arr, new_row))
print("With new row:\n", arr)

# Add column
new_col = np.array([7, 8, 9])
arr = np.column_stack((arr, new_col))
print("\nWith new column:\n", arr)

With new row:
 [[1 2]
 [3 4]
 [5 6]]

With new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


    vstack() vertically stacks (adds rows)

    column_stack() adds columns

In [15]:
arr = np.array([1, 2, 3, 4])

print("Reversed:", np.flip(arr))

# 2D reversal
arr_2d = np.array([[1, 2], [3, 4]])
print("\nRow-reversed:\n", np.flip(arr_2d, axis=0))
print("Column-reversed:\n", np.flip(arr_2d, axis=1))

Reversed: [4 3 2 1]

Row-reversed:
 [[3 4]
 [1 2]]
Column-reversed:
 [[2 1]
 [4 3]]


    flip() reverses element order

    axis controls direction in multi-D arrays

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("A + B:\n", np.add(A, B))

# Subtraction
print("\nA - B:\n", np.subtract(A, B))

# Multiplication
print("\nA × B:\n", np.matmul(A, B))

# Transpose
print("\nA Transpose:\n", A.T)

A + B:
 [[ 6  8]
 [10 12]]

A - B:
 [[-4 -4]
 [-4 -4]]

A × B:
 [[19 22]
 [43 50]]

A Transpose:
 [[1 3]
 [2 4]]


    add(), subtract() are element-wise

    matmul() performs true matrix multiplication

    .T property transposes matrix